### ISSUE TITLE
next bot script has invalid file extension

### ISSUE THREAD

**Issue by headsmasher8557** [fofl12/sc#2]
this is a major issue please remove the space from ". lua"!

**Comment by raymonable** [comment]
YEA COPMSURG

DO IT
COMMIT IT

COMMIT IT NOW

**Comment by raymonable** [comment]
COMGSUTRGH.
YOU HAVEN'T COMMITED IT.

**Comment by raymonable** [comment]
COMSURG.

**Comment by raymonable** [comment]
FUCKING COMMIT IT NOW

**Comment by headsmasher8557** [comment]
real

**Comment by fofl12** [comment]
shut the fuck up

**Comment by headsmasher8557** [comment]
:(

**Comment by fofl12** [comment]
cope

**Comment by raymonable** [comment]
THIS IS NOT COMPLETE

**Comment by raymonable** [comment]
LIAR

**Comment by fofl12** [comment]
Ok. I will fix this terrible prdeicamejtjrekyjtlers7

**Comment by github-user123456789** [comment]
fix it you noob

**Comment by headsmasher8557** [comment]
woo!

**Comment by github-user123456789** [comment]
thank you!!!!!!!!!

**Comment by raymonable** [comment]
FUCK YOU BITCH

**Comment by raymonable** [comment]
YOU DIDN'T FIX IT YOU JUST ADDED .LUA TO THE END

**Comment by raymonable** [comment]
FIX IT PROEPRLYOR FUCKS AKE!!!

`nextbotx,.lua`

**Comment by fofl12** [comment]
shut the fuck up

**Comment by raymonable** [comment]
fuck you
